baseURL = "/"
languageCode = "de-DE"
title = "Makerspace Kaarst | Home"
theme = "slate"
defaultContentLanguage = "de"

#publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = false
#[[ params.nav ]]
#name = "Original"
#tag = "original"
#icon = "star"


[[ params.nav ]]
name = "kontakt"
tag = "kontakt"
icon = "envelope-open"

[[ params.nav ]]
name = "github"
tag = "github"
icon = "github"

[[ params.nav ]]
name = "text"
tag = "text"
icon = "pencil"

[languages]
  [languages.de]
    contentDir = "content/deutsch"
    languageName = "de"
    weight = 1

  [languages.en]
    contentDir = "content/english"
    languageName = "en"
    weight = 2
