baseURL = "/"
languageCode = "de-DE"
title = "Minkorrekt Linksammlung"
theme = "slate"

#publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = false

#[[ params.nav ]]
#name = "Original"
#tag = "original"
#icon = "star"


[[ params.nav ]]
name = "kontakt"
tag = "kontakt"
icon = "envelope-open"

[[ params.nav ]]
name = "github"
tag = "github"
icon = "github"
